# Generated by Django 4.1.5 on 2023-01-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RTOadmin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_username', models.CharField(max_length=50)),
                ('admin_password', models.CharField(max_length=50)),
                ('admin_created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
