# Generated by Django 4.1.5 on 2023-03-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rto', '0006_rename_name_challan_owner_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='offender_email_id',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='challan',
            name='offender_mobile_no',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
