# Generated by Django 4.1.5 on 2023-03-15 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rto', '0007_alter_challan_offender_email_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challan',
            old_name='offense',
            new_name='rule_code',
        ),
        migrations.RemoveField(
            model_name='challan',
            name='rule_id',
        ),
    ]
