# Generated by Django 4.1.5 on 2023-02-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Police',
            fields=[
                ('police_id', models.AutoField(primary_key=True, serialize=False)),
                ('police_username', models.CharField(default=None, max_length=50)),
                ('police_password', models.CharField(max_length=50)),
                ('police_firstname', models.CharField(default=None, max_length=50)),
                ('police_lastname', models.CharField(default=None, max_length=50)),
                ('police_age', models.IntegerField(default=None)),
                ('police_birth_date', models.DateField(default=None)),
                ('police_joing_date', models.DateField(default=None)),
                ('police_address', models.CharField(default=None, max_length=100)),
                ('police_gender', models.CharField(default=None, max_length=20)),
                ('police_last_login', models.CharField(default=None, max_length=30)),
                ('police_created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
