# Generated by Django 4.1.5 on 2023-03-15 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0002_challan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Challan',
        ),
    ]
